# Generated by Django 4.2 on 2023-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
